---
abstract: 'A MessagePack converting processor'
author:
  - 'Alexei Znamensky <russoz@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DataFlow-Proc-MessagePack
requires:
  Data::MessagePack: 0
  DataFlow::Proc::Converter: 0
  Moose: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/russoz/XXXXXX.git
version: 1.111710
